### ISSUE TITLE
ROCm Backend Status Tracker

### ISSUE THREAD

**Issue by pnunna93** [TimDettmers/bitsandbytes#1271]
This issue summarizes and tracks the current status of ROCm enablement for BitsandBytes.

- [x] Enable ROCm backend for bitsandbytes - Supported from ROCm 6.1
- [x] Update ROCm install instructions in official bitsandbytes documentation
- [x] Provide AMD GPU to public CI
- [ ] Enable ROCm build in public CI - PR opened at https://github.com/TimDettmers/bitsandbytes/pull/1255
- [ ] Provide packaging/wheels support for ROCm - In progress

The completed changes are in multi-backend-refactor branch and will be merged into main once multi-backend design is finalized.

cc: @Titus-von-Koeller @sunway513 @amathews-amd

**Comment by Titus-von-Koeller** [comment]
@pnunna93 

PyTorch 2.4 is built with ROCm 6.1, we should be sure that the bundled ROCm binaries are compatible with the newest PyTorch release that just came out.

**Comment by Titus-von-Koeller** [comment]
@pnunna93 I'm planning to do the alpha release with prebuilt wheels in the beginning of next week. Do you think you'll have the last item on this list checked by then? I think it would be important to prioritize this so we can move forward and get more user feedback.

**Comment by pnunna93** [comment]
@Titus-von-Koeller Sure, I have been ironing out some details and got most of the info I need. I will start testing and open a PR early next week.

**Comment by matthewdouglas** [comment]
I'm going to close this as we've started shipping ROCm wheels to PyPI since [v0.49.0](https://github.com/bitsandbytes-foundation/bitsandbytes/releases/tag/0.49.0). We can track more specific issues separately, but we'll consider this feature request complete.
